name: Contributor List Update

on:
  push:
    branches:
      - main

jobs:
  contrib-readme-job-CN:
    runs-on: ubuntu-latest
    name: Update Contributors List CN
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  contrib-readme-job-EN:
    runs-on: ubuntu-latest
    needs: contrib-readme-job-CN
    name: Update Contributors List EN
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        with:
          readme_path: README_EN.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
