name: Django CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "README.md"
      - "README_EN.md"
      - ".github/pull_request_template.md"
      - ".github/workflows/contributors_update.yml"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "README.md"
      - "README_EN.md"
      - ".github/pull_request_template.md"
      - ".github/workflows/contributors_update.yml"

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python ./Blog/manage.py test
